spring.application.name=nftfabric

server.port=8080

# ==============================
# Hyperledger Fabric
# ==============================

# MSP ID ??? Org1
fabric.msp-id=Org1MSP

# ???? ? ???????????????? (?? src/main/resources)
fabric.cert-path=cert.pem
fabric.key-path=key.pem
fabric.tls-cert-path=ca.crt

# Peer Org1 (test-network)
fabric.peer-host=127.0.0.1
fabric.peer-port=7051

# ==============================
# PostgreSQL
# ==============================
#spring.datasource.url=jdbc:postgresql://localhost:5432/path_of_talante
#spring.datasource.username=postgres
#spring.datasource.password=GhBDtn123
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# Actuator
# ==============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
